-- Append-only audit trail for every PaymentStatus transition a transaction goes through.
-- transactions.status stays as the fast "current state" column; this table is the history
-- transactions never kept (architecture-review 06-PAYMENT-GATEWAY-DESIGN-REVIEW.md).
-- "Current status" is definitionally the latest row here, ordered by occurred_at.
CREATE TABLE payment_events (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id     BIGINT       NOT NULL REFERENCES transactions(id),
    external_reference VARCHAR(50)  NOT NULL,
    event_type         VARCHAR(20)  NOT NULL, -- reuses PaymentStatus values: PENDING/SUCCESSFUL/FAILED/TIMEOUT
    raw_payload        JSONB,
    occurred_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_payment_events_transaction_id ON payment_events (transaction_id);
CREATE INDEX idx_payment_events_external_reference ON payment_events (external_reference);
