-- Baseline migration: captures the schema as it currently exists after
-- Hibernate ddl-auto=update. From here on, ddl-auto=validate and all schema
-- changes go through Flyway. Table layout lands in the schema configured via
-- spring.flyway.schemas (the service's own "payment" schema on Supabase, or
-- a freshly created "payment" schema in the local dev Postgres instance).

CREATE TABLE transactions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_reference  VARCHAR(50)     NOT NULL UNIQUE,
    amount              NUMERIC(10,2)   NOT NULL,
    currency            VARCHAR(5)      NOT NULL,
    phone_number        VARCHAR(20),
    machine_id          VARCHAR(30)     NOT NULL,
    pulse_count         INTEGER         NOT NULL,
    cycle_duration      INTEGER         NOT NULL,
    description         VARCHAR(200),
    status              VARCHAR(20)     NOT NULL
        CHECK (status IN ('PENDING', 'SUCCESSFUL', 'FAILED', 'TIMEOUT')),
    payment_provider    VARCHAR(20)     NOT NULL
        CHECK (payment_provider IN ('CAMPAY', 'MTN', 'ORANGE_MONEY')),
    provider_reference  VARCHAR(100),
    failure_reason      VARCHAR(300),
    rfid_card_uid       VARCHAR(50),
    timeout_at          TIMESTAMP(6),
    created_at          TIMESTAMP(6)    NOT NULL,
    updated_at          TIMESTAMP(6)
);

CREATE TABLE rfid_cards (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_uid     VARCHAR(50)    NOT NULL UNIQUE,
    owner_name   VARCHAR(100),
    phone_number VARCHAR(20),
    balance      NUMERIC(10,2)  NOT NULL,
    currency     VARCHAR(5)     NOT NULL,
    is_active    BOOLEAN        NOT NULL,
    created_at   TIMESTAMP(6)   NOT NULL,
    updated_at   TIMESTAMP(6)
);

CREATE TABLE topup_transactions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference           VARCHAR(50)    NOT NULL UNIQUE,
    rfid_card_uid       VARCHAR(50)    NOT NULL,
    amount              NUMERIC(10,2)  NOT NULL,
    currency            VARCHAR(5)     NOT NULL,
    phone_number        VARCHAR(20),
    channel             VARCHAR(20)    NOT NULL
        CHECK (channel IN ('CAMPAY', 'MTN', 'ORANGE_MONEY', 'CASH')),
    status              VARCHAR(20)    NOT NULL
        CHECK (status IN ('PENDING', 'SUCCESSFUL', 'FAILED', 'TIMEOUT')),
    provider_reference  VARCHAR(100),
    failure_reason      VARCHAR(300),
    created_at          TIMESTAMP(6)   NOT NULL,
    updated_at          TIMESTAMP(6)
);
