export const styles = {
  // Clock Card
  clockCard: {
    container: 'card',
    header: 'card-header',
    title: 'card-title',
    body: 'p-6',
    statusContainer: 'flex items-center justify-between mb-6',
    statusBadge: {
      base: 'flex items-center px-4 py-2 rounded-full text-sm font-medium',
      clockedIn: 'bg-success-100 text-success-700',
      clockedOut: 'bg-gray-100 text-gray-700',
    },
    statusIcon: 'w-4 h-4 mr-2',
    durationContainer: 'text-center mb-6',
    durationLabel: 'text-sm text-gray-500 mb-1',
    durationValue: 'text-4xl font-bold text-gray-900',
    startTime: 'text-sm text-gray-500 mt-2',
    buttonContainer: 'flex justify-center',
    clockButton: {
      base: 'flex items-center px-8 py-3 rounded-lg font-medium text-lg transition-colors',
      clockIn: 'bg-success-600 hover:bg-success-700 text-white',
      clockOut: 'bg-danger-600 hover:bg-danger-700 text-white',
      disabled: 'opacity-50 cursor-not-allowed',
    },
    buttonIcon: 'w-5 h-5 mr-2',
  },

  // Entry Table
  entryTable: {
    container: 'card overflow-hidden',
    header: 'card-header',
    title: 'card-title',
    tableContainer: 'overflow-x-auto',
    table: 'min-w-full divide-y divide-gray-200',
    thead: 'bg-gray-50',
    th: 'px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider',
    tbody: 'bg-white divide-y divide-gray-200',
    tr: 'hover:bg-gray-50',
    td: 'px-6 py-4 whitespace-nowrap text-sm',
    tdText: 'text-gray-900',
    tdSubtext: 'text-gray-500',
    badge: {
      base: 'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium',
      clockIn: 'bg-success-100 text-success-700',
      clockOut: 'bg-primary-100 text-primary-700',
      automatic: 'bg-gray-100 text-gray-700',
      manual: 'bg-warning-100 text-warning-700',
    },
    deleteButton: 'text-danger-600 hover:text-danger-900',
    emptyState: 'text-center py-12 text-gray-500',
    loadingState: 'animate-pulse bg-gray-200 rounded h-4',
  },

  // Summary Card
  summaryCard: {
    container: 'card',
    header: 'card-header',
    title: 'card-title',
    body: 'p-6',
    grid: 'grid grid-cols-2 gap-6',
    statCard: 'text-center p-4 bg-gray-50 rounded-lg',
    statLabel: 'text-sm text-gray-500 mb-1',
    statValue: 'text-2xl font-bold text-gray-900',
    sessionsList: 'mt-6 space-y-3',
    sessionItem: 'flex items-center justify-between p-3 bg-gray-50 rounded-lg',
    sessionDate: 'text-sm font-medium text-gray-900',
    sessionTime: 'text-xs text-gray-500',
    sessionDuration: 'text-sm font-medium',
    sessionOpen: 'text-success-600',
    sessionClosed: 'text-gray-700',
  },

  // Modal
  modal: {
    overlay: 'fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50',
    container: 'bg-white rounded-lg shadow-xl max-w-md w-full mx-4',
    header: 'flex items-center justify-between p-4 border-b',
    title: 'text-lg font-semibold text-gray-900',
    closeButton: 'text-gray-400 hover:text-gray-500',
    body: 'p-4 space-y-4',
    footer: 'flex justify-end gap-3 p-4 border-t',
    label: 'block text-sm font-medium text-gray-700 mb-1',
    input: 'w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-primary-500',
    select: 'w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-primary-500',
    cancelButton: 'px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50',
    submitButton: 'px-4 py-2 text-sm font-medium text-white bg-primary-600 rounded-lg hover:bg-primary-700',
  },
} as const;
