// API Hooks
export {
  useDashboardSummary,
  useDashboardStats,
  useMachines,
  useMachine,
  useMachineHistory,
  useTransactions,
  useTransaction,
  useRevenueSummary,
  useRevenueByProvider,
  useRevenueByProgram,
  useRevenueByMachine,
  useRevenueTrends,
  useMaintenanceAlerts,
  useMaintenanceHistory,
  useDailyReport,
  useMonthlyReport,
  useExpenses,
  useReconciliation,
  useDiscrepancies,
  usePolling,
  useDashboardWithPolling,
  useMachinesWithPolling,
} from './useApi';
