-- Phase 3 (architecture-review/03-MIGRATION-TODO.md): provision the
-- `payment` schema tables in smartlaundry-dev/smartlaundry-test ahead of
-- cutover. Mirrors PaymentManagementService's V1__baseline_schema.sql and
-- V2__outbox_and_idempotency.sql (feature/p3-payment-supabase-consolidation),
-- which target the `payment` schema via spring.flyway.schemas=payment.

SET search_path TO payment;

-- V1__baseline_schema
CREATE TABLE transactions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_reference  VARCHAR(50)     NOT NULL UNIQUE,
    amount              NUMERIC(10,2)   NOT NULL,
    currency            VARCHAR(5)      NOT NULL,
    phone_number        VARCHAR(20),
    machine_id          VARCHAR(30)     NOT NULL,
    pulse_count         INTEGER         NOT NULL,
    cycle_duration      INTEGER         NOT NULL,
    description         VARCHAR(200),
    status              VARCHAR(20)     NOT NULL
        CHECK (status IN ('PENDING', 'SUCCESSFUL', 'FAILED', 'TIMEOUT')),
    payment_provider    VARCHAR(20)     NOT NULL
        CHECK (payment_provider IN ('CAMPAY', 'MTN', 'ORANGE_MONEY')),
    provider_reference  VARCHAR(100),
    failure_reason      VARCHAR(300),
    rfid_card_uid       VARCHAR(50),
    timeout_at          TIMESTAMP(6),
    created_at          TIMESTAMP(6)    NOT NULL,
    updated_at          TIMESTAMP(6)
);

CREATE TABLE rfid_cards (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_uid     VARCHAR(50)    NOT NULL UNIQUE,
    owner_name   VARCHAR(100),
    phone_number VARCHAR(20),
    balance      NUMERIC(10,2)  NOT NULL,
    currency     VARCHAR(5)     NOT NULL,
    is_active    BOOLEAN        NOT NULL,
    created_at   TIMESTAMP(6)   NOT NULL,
    updated_at   TIMESTAMP(6)
);

CREATE TABLE topup_transactions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference           VARCHAR(50)    NOT NULL UNIQUE,
    rfid_card_uid       VARCHAR(50)    NOT NULL,
    amount              NUMERIC(10,2)  NOT NULL,
    currency            VARCHAR(5)     NOT NULL,
    phone_number        VARCHAR(20),
    channel             VARCHAR(20)    NOT NULL
        CHECK (channel IN ('CAMPAY', 'MTN', 'ORANGE_MONEY', 'CASH')),
    status              VARCHAR(20)    NOT NULL
        CHECK (status IN ('PENDING', 'SUCCESSFUL', 'FAILED', 'TIMEOUT')),
    provider_reference  VARCHAR(100),
    failure_reason      VARCHAR(300),
    created_at          TIMESTAMP(6)   NOT NULL,
    updated_at          TIMESTAMP(6)
);

-- V2__outbox_and_idempotency
CREATE TABLE outbox (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(50)  NOT NULL,
    aggregate_id   VARCHAR(100) NOT NULL,
    event_type     VARCHAR(100) NOT NULL,
    payload        JSONB        NOT NULL,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    processed_at   TIMESTAMPTZ
);

CREATE INDEX idx_outbox_unprocessed ON outbox (created_at) WHERE processed_at IS NULL;

CREATE TABLE idempotency_keys (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(100) NOT NULL UNIQUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    expires_at      TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_idempotency_keys_expires_at ON idempotency_keys (expires_at);

-- Flyway baseline: mark V1-V2 as already applied so the service's Flyway run
-- doesn't try to recreate these objects on first connect.
CREATE TABLE flyway_schema_history (
    installed_rank INT NOT NULL PRIMARY KEY,
    version VARCHAR(50),
    description VARCHAR(200) NOT NULL,
    type VARCHAR(20) NOT NULL,
    script VARCHAR(1000) NOT NULL,
    checksum INT,
    installed_by VARCHAR(100) NOT NULL,
    installed_on TIMESTAMPTZ NOT NULL DEFAULT now(),
    execution_time INT NOT NULL,
    success BOOLEAN NOT NULL
);
CREATE INDEX flyway_schema_history_s_idx ON flyway_schema_history (success);

INSERT INTO flyway_schema_history (installed_rank, version, description, type, script, checksum, installed_by, execution_time, success)
VALUES (1, '2', 'Baseline (manual P2/P3 provisioning)', 'BASELINE', '<< Flyway Baseline >>', NULL, current_user, 0, true);
