-- Baseline migration: captures the schema as it currently exists after
-- Hibernate ddl-auto=update. From here on, ddl-auto=validate and all schema
-- changes go through Flyway. Table layout lands in the schema configured via
-- spring.flyway.schemas (the service's own "machine" schema on Supabase, or
-- a freshly created "machine" schema in the local dev Postgres instance).

CREATE TABLE machines (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id             VARCHAR(30)     NOT NULL UNIQUE,
    type                   VARCHAR(10)     NOT NULL
        CHECK (type IN ('WASHER', 'DRYER')),
    comm_protocol          VARCHAR(10)     NOT NULL
        CHECK (comm_protocol IN ('EQLINK', 'MODBUS', 'MQTT')),
    status                 VARCHAR(20)     NOT NULL
        CHECK (status IN ('IDLE', 'RUNNING', 'PAUSED', 'FINISHED', 'ERROR', 'MAINTENANCE', 'OFFLINE')),
    brand                  VARCHAR(50),
    model                  VARCHAR(50),
    zone                   VARCHAR(30),
    position               INTEGER,
    is_online              BOOLEAN         NOT NULL,
    door_locked            BOOLEAN,
    last_heartbeat         TIMESTAMP(6),
    current_cycle_type     VARCHAR(20)
        CHECK (current_cycle_type IN ('NONE', 'QUICK', 'NORMAL', 'HEAVY', 'DELICATE', 'SANITIZE', 'COTTON_40', 'COTTON_60', 'COTTON_90', 'LOW_HEAT', 'MEDIUM_HEAT', 'HIGH_HEAT')),
    cycle_duration_minutes INTEGER,
    cycle_progress         INTEGER,
    cycle_started_at       TIMESTAMP(6),
    cycle_ends_at          TIMESTAMP(6),
    temperature            REAL,
    humidity               REAL,
    vibration              REAL,
    water_level            REAL,
    power_consumption      DOUBLE PRECISION,
    spin_speed             INTEGER,
    error_code             VARCHAR(20),
    error_message          VARCHAR(200),
    total_cycles           INTEGER,
    cycles_since_service   INTEGER,
    last_service_date      TIMESTAMP(6),
    created_at             TIMESTAMP(6)    NOT NULL,
    updated_at             TIMESTAMP(6)
);

CREATE TABLE machine_cycles (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id             VARCHAR(30)     NOT NULL,
    cycle_type             VARCHAR(20)     NOT NULL
        CHECK (cycle_type IN ('NONE', 'QUICK', 'NORMAL', 'HEAVY', 'DELICATE', 'SANITIZE', 'COTTON_40', 'COTTON_60', 'COTTON_90', 'LOW_HEAT', 'MEDIUM_HEAT', 'HIGH_HEAT')),
    status                 VARCHAR(20)     NOT NULL
        CHECK (status IN ('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED')),
    duration_minutes       INTEGER         NOT NULL,
    pulse_count            INTEGER,
    rfid_card_uid          VARCHAR(50),
    transaction_reference  VARCHAR(50),
    started_at             TIMESTAMP(6),
    ends_at                TIMESTAMP(6),
    completed_at           TIMESTAMP(6),
    created_at             TIMESTAMP(6)    NOT NULL
);

CREATE TABLE machine_events (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id             VARCHAR(30)     NOT NULL,
    event_type             VARCHAR(50)     NOT NULL,
    previous_status        VARCHAR(20),
    new_status             VARCHAR(20),
    details                VARCHAR(500),
    rfid_card_uid          VARCHAR(50),
    transaction_reference  VARCHAR(50),
    created_at             TIMESTAMP(6)    NOT NULL
);

CREATE TABLE reservations (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id             VARCHAR(30)     NOT NULL,
    reservation_code       VARCHAR(20)     NOT NULL UNIQUE,
    status                 VARCHAR(20)     NOT NULL
        CHECK (status IN ('PENDING_PAYMENT', 'ACTIVE', 'USED', 'EXPIRED', 'CANCELLED')),
    slot_start             TIMESTAMP(6)    NOT NULL,
    slot_end               TIMESTAMP(6)    NOT NULL,
    fee_amount             INTEGER         NOT NULL,
    currency               VARCHAR(10),
    customer_phone         VARCHAR(30),
    transaction_reference  VARCHAR(80),
    activated_at           TIMESTAMP(6),
    used_at                TIMESTAMP(6),
    created_at             TIMESTAMP(6)    NOT NULL
);

CREATE INDEX idx_res_code_machine ON reservations (reservation_code, machine_id);
CREATE INDEX idx_res_machine_status ON reservations (machine_id, status);
